export type Rematricula = {
    id?: string,
    name: string,
    age?: string,
    datebirth?: string,
    unity: string,
    dependency?: string,
    course: string,
    class?: string,
    financy?: string,
    quota?: number,
    alimentation?: string,
    nextcourse?: string,
    regime?: string,
}